name: Release to Maven Central
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up JDK 8
        uses: actions/setup-java@v5
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Update pom version
        run: mvn versions:set -DnewVersion=${{ steps.version.outputs.VERSION }} versions:commit

      # Sonatype 官方的发布 Action，所有步骤都帮你做好了！
      - name: Publish to Maven Central
        uses: sonatype/central-publish-action@v1
        with:
          username: ${{ secrets.CENTRAL_USER }}
          password: ${{ secrets.CENTRAL_PWD }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          gpg-secret-key: ${{ secrets.GPG_SECRET_KEY }}
          args: -DskipTests